import type { Act, PlotPoint } from "./types";

const now = new Date().toISOString();

export const mockActs: Act[] = [
  {
    id: "act_1",
    storyId: "book_1",
    title: "The Fractured Beginning",
    type: "setup",
    order: 1,
    summary:
      "The protagonist discovers an ancient mirror artifact tied to a forgotten war.",
    eventIds: ["event_1", "event_2"],
    startEventId: "event_1",
    endEventId: "event_2",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "act_2",
    storyId: "book_1",
    title: "Ashes of Truth",
    type: "rising_action",
    order: 2,
    summary: "Enemies close in as hidden powers awaken across the kingdom.",
    eventIds: ["event_3", "event_4"],
    startEventId: "event_3",
    endEventId: "event_4",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "act_3",
    storyId: "book_1",
    title: "The Glass Throne",
    type: "climax",
    order: 3,
    summary:
      "The final confrontation determines the fate of the shattered realm.",
    eventIds: ["event_5"],
    startEventId: "event_5",
    endEventId: "event_5",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockPlotPoints: PlotPoint[] = [
  {
    id: "plot_1",
    storyId: "book_1",
    title: "Mirror Awakening",
    description:
      "The protagonist accidentally activates the ancient mirror relic.",
    type: "inciting_incident",
    actId: "act_1",
    order: 1,
    eventId: "event_1",
    characterIds: ["char_1"],
    locationIds: ["loc_1"],
    importance: "critical",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "plot_2",
    storyId: "book_1",
    title: "The Hidden Archive",
    description: "A secret library reveals the truth behind the celestial war.",
    type: "reveal",
    actId: "act_2",
    order: 2,
    eventId: "event_3",
    characterIds: ["char_1", "char_2"],
    locationIds: ["loc_2"],
    importance: "high",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "plot_3",
    storyId: "book_1",
    title: "Betrayal at Dawn",
    description: "A trusted ally sides with the enemy to protect their family.",
    type: "plot_twist",
    actId: "act_2",
    order: 3,
    eventId: "event_4",
    characterIds: ["char_2"],
    locationIds: ["loc_3"],
    importance: "critical",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "plot_4",
    storyId: "book_1",
    title: "The Final Reflection",
    description:
      "The protagonist accepts their role and confronts the antagonist.",
    type: "climax_moment",
    actId: "act_3",
    order: 4,
    eventId: "event_5",
    characterIds: ["char_1", "char_3"],
    locationIds: ["loc_4"],
    importance: "critical",
    createdAt: now,
    updatedAt: now,
  },
];
