import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/lib/components/theme-provider';

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Apricity',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${lexend.variable} antialiased font-sans font-medium`}
      >
        <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    {children}
                  </ThemeProvider>
      </body>
    </html>
  );
}
