import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { FileSystemItem } from './features/file-system/types';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
export type Result<T, E> = { ok: true; data: T } | { ok: false; error: E };
export function ok<T>(data: T): Result<T, never> {
  return { ok: true, data };
}

export function err<E>(error: E) {
  return { ok: false, error } as const;
}



export const sampleFileSystemData: FileSystemItem[] = [
  // Root folders
  {
    id: 'folder-1',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Documentation',
    type: 'folder',
    parentId: null,
    order: 0,
    isPinned: true,
    tags: ['docs', 'reference'],
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-20T14:30:00Z'),
  },
  {
    id: 'folder-2',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Components',
    type: 'folder',
    parentId: null,
    order: 1,
    isPinned: true,
    tags: ['code', 'ui'],
    createdAt: new Date('2024-01-15T10:05:00Z'),
    updatedAt: new Date('2024-01-22T09:15:00Z'),
  },
  {
    id: 'folder-3',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Assets',
    type: 'folder',
    parentId: null,
    order: 2,
    isPinned: false,
    tags: ['images', 'media'],
    createdAt: new Date('2024-01-15T10:10:00Z'),
    updatedAt: new Date('2024-01-18T16:45:00Z'),
  },
  {
    id: 'folder-4',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Tests',
    type: 'folder',
    parentId: null,
    order: 3,
    isPinned: false,
    tags: ['testing', 'quality'],
    createdAt: new Date('2024-01-16T11:20:00Z'),
    updatedAt: new Date('2024-01-21T13:00:00Z'),
  },

  // Nested folders in Documentation
  {
    id: 'folder-5',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'API',
    type: 'folder',
    parentId: 'folder-1',
    order: 0,
    isPinned: false,
    tags: ['api', 'reference'],
    createdAt: new Date('2024-01-16T09:00:00Z'),
    updatedAt: new Date('2024-01-19T10:30:00Z'),
  },
  {
    id: 'folder-6',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Guides',
    type: 'folder',
    parentId: 'folder-1',
    order: 1,
    isPinned: false,
    tags: ['tutorials', 'how-to'],
    createdAt: new Date('2024-01-16T09:15:00Z'),
    updatedAt: new Date('2024-01-20T11:00:00Z'),
  },

  // Nested folders in Components
  {
    id: 'folder-7',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Common',
    type: 'folder',
    parentId: 'folder-2',
    order: 0,
    isPinned: false,
    tags: ['reusable', 'shared'],
    createdAt: new Date('2024-01-17T08:30:00Z'),
    updatedAt: new Date('2024-01-22T15:20:00Z'),
  },
  {
    id: 'folder-8',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Features',
    type: 'folder',
    parentId: 'folder-2',
    order: 1,
    isPinned: false,
    tags: ['business-logic'],
    createdAt: new Date('2024-01-17T08:45:00Z'),
    updatedAt: new Date('2024-01-21T14:10:00Z'),
  },

  // Files in root
  {
    id: 'file-1',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'README.md',
    type: 'file',
    parentId: null,
    content: '# Project Alpha\n\nThis is the main project documentation.',
    size: 1024,
    order: 4,
    isPinned: true,
    tags: ['documentation', 'important'],
    createdAt: new Date('2024-01-15T09:00:00Z'),
    updatedAt: new Date('2024-01-23T10:00:00Z'),
  },
  {
    id: 'file-2',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'package.json',
    type: 'file',
    parentId: null,
    content: '{\n  "name": "project-alpha",\n  "version": "1.0.0"\n}',
    size: 512,
    order: 5,
    isPinned: false,
    tags: ['config'],
    createdAt: new Date('2024-01-15T09:10:00Z'),
    updatedAt: new Date('2024-01-20T12:00:00Z'),
  },
  {
    id: 'file-3',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: '.gitignore',
    type: 'file',
    parentId: null,
    content: 'node_modules/\ndist/\n.env',
    size: 256,
    order: 6,
    isPinned: false,
    tags: ['config', 'git'],
    createdAt: new Date('2024-01-15T09:20:00Z'),
    updatedAt: new Date('2024-01-15T09:20:00Z'),
  },

  // Files in Documentation/API
  {
    id: 'file-4',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'authentication.md',
    type: 'file',
    parentId: 'folder-5',
    content: '# Authentication\n\nDetails about API authentication mechanisms.',
    size: 2048,
    order: 0,
    isPinned: true,
    tags: ['api', 'security'],
    createdAt: new Date('2024-01-17T10:00:00Z'),
    updatedAt: new Date('2024-01-22T11:30:00Z'),
  },
  {
    id: 'file-5',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'endpoints.md',
    type: 'file',
    parentId: 'folder-5',
    content: '# API Endpoints\n\n## Users\n- GET /api/users\n- POST /api/users',
    size: 3072,
    order: 1,
    isPinned: false,
    tags: ['api', 'reference'],
    createdAt: new Date('2024-01-17T10:30:00Z'),
    updatedAt: new Date('2024-01-21T09:45:00Z'),
  },
  {
    id: 'file-6',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'rate-limiting.md',
    type: 'file',
    parentId: 'folder-5',
    content: '# Rate Limiting\n\nAPI rate limits: 100 requests per minute.',
    size: 1536,
    order: 2,
    isPinned: false,
    tags: ['api', 'performance'],
    createdAt: new Date('2024-01-18T14:00:00Z'),
    updatedAt: new Date('2024-01-19T16:20:00Z'),
  },

  // Files in Documentation/Guides
  {
    id: 'file-7',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'getting-started.md',
    type: 'file',
    parentId: 'folder-6',
    content: '# Getting Started\n\n1. Clone the repository\n2. Install dependencies',
    size: 2560,
    order: 0,
    isPinned: true,
    tags: ['tutorial', 'beginner'],
    createdAt: new Date('2024-01-17T11:00:00Z'),
    updatedAt: new Date('2024-01-23T08:30:00Z'),
  },
  {
    id: 'file-8',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'deployment.md',
    type: 'file',
    parentId: 'folder-6',
    content: '# Deployment Guide\n\nSteps to deploy the application to production.',
    size: 4096,
    order: 1,
    isPinned: false,
    tags: ['deployment', 'devops'],
    createdAt: new Date('2024-01-18T13:00:00Z'),
    updatedAt: new Date('2024-01-22T14:45:00Z'),
  },
  {
    id: 'file-9',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'troubleshooting.md',
    type: 'file',
    parentId: 'folder-6',
    content: '# Troubleshooting\n\nCommon issues and their solutions.',
    size: 3584,
    order: 2,
    isPinned: false,
    tags: ['support', 'debugging'],
    createdAt: new Date('2024-01-19T09:30:00Z'),
    updatedAt: new Date('2024-01-21T10:15:00Z'),
  },

  // Files in Components/Common
  {
    id: 'file-10',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Button.tsx',
    type: 'file',
    parentId: 'folder-7',
    content: 'import React from "react";\n\nexport const Button = () => {\n  return <button>Click me</button>;\n};',
    size: 1800,
    order: 0,
    isPinned: true,
    tags: ['component', 'ui', 'react'],
    createdAt: new Date('2024-01-18T10:00:00Z'),
    updatedAt: new Date('2024-01-23T11:20:00Z'),
  },
  {
    id: 'file-11',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Input.tsx',
    type: 'file',
    parentId: 'folder-7',
    content: 'import React from "react";\n\nexport const Input = () => {\n  return <input type="text" />;\n};',
    size: 1600,
    order: 1,
    isPinned: false,
    tags: ['component', 'ui', 'react'],
    createdAt: new Date('2024-01-18T10:30:00Z'),
    updatedAt: new Date('2024-01-22T09:00:00Z'),
  },
  {
    id: 'file-12',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Modal.tsx',
    type: 'file',
    parentId: 'folder-7',
    content: 'import React from "react";\n\nexport const Modal = ({ children }) => {\n  return <div className="modal">{children}</div>;\n};',
    size: 2200,
    order: 2,
    isPinned: false,
    tags: ['component', 'ui', 'react'],
    createdAt: new Date('2024-01-18T11:00:00Z'),
    updatedAt: new Date('2024-01-21T15:30:00Z'),
  },
  {
    id: 'file-13',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Card.tsx',
    type: 'file',
    parentId: 'folder-7',
    content: 'import React from "react";\n\nexport const Card = ({ title, content }) => {\n  return <div className="card"><h3>{title}</h3><p>{content}</p></div>;\n};',
    size: 2400,
    order: 3,
    isPinned: false,
    tags: ['component', 'ui', 'react'],
    createdAt: new Date('2024-01-19T08:00:00Z'),
    updatedAt: new Date('2024-01-23T12:45:00Z'),
  },

  // Files in Components/Features
  {
    id: 'file-14',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'UserProfile.tsx',
    type: 'file',
    parentId: 'folder-8',
    content: 'import React from "react";\n\nexport const UserProfile = () => {\n  return <div>User Profile Component</div>;\n};',
    size: 2800,
    order: 0,
    isPinned: false,
    tags: ['component', 'feature', 'user'],
    createdAt: new Date('2024-01-19T09:00:00Z'),
    updatedAt: new Date('2024-01-22T16:00:00Z'),
  },
  {
    id: 'file-15',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Dashboard.tsx',
    type: 'file',
    parentId: 'folder-8',
    content: 'import React from "react";\n\nexport const Dashboard = () => {\n  return <div>Dashboard Component</div>;\n};',
    size: 3200,
    order: 1,
    isPinned: true,
    tags: ['component', 'feature', 'dashboard'],
    createdAt: new Date('2024-01-19T10:00:00Z'),
    updatedAt: new Date('2024-01-23T09:30:00Z'),
  },
  {
    id: 'file-16',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Settings.tsx',
    type: 'file',
    parentId: 'folder-8',
    content: 'import React from "react";\n\nexport const Settings = () => {\n  return <div>Settings Component</div>;\n};',
    size: 2600,
    order: 2,
    isPinned: false,
    tags: ['component', 'feature', 'settings'],
    createdAt: new Date('2024-01-20T08:30:00Z'),
    updatedAt: new Date('2024-01-22T10:20:00Z'),
  },

  // Files in Assets
  {
    id: 'file-17',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'logo.svg',
    type: 'file',
    parentId: 'folder-3',
    content: '<svg xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40" /></svg>',
    size: 512,
    order: 0,
    isPinned: true,
    tags: ['image', 'branding'],
    createdAt: new Date('2024-01-16T14:00:00Z'),
    updatedAt: new Date('2024-01-20T13:15:00Z'),
  },
  {
    id: 'file-18',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'hero-image.jpg',
    type: 'file',
    parentId: 'folder-3',
    content: 'binary-image-data-placeholder',
    size: 102400,
    order: 1,
    isPinned: false,
    tags: ['image', 'hero'],
    createdAt: new Date('2024-01-17T15:00:00Z'),
    updatedAt: new Date('2024-01-17T15:00:00Z'),
  },
  {
    id: 'file-19',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'icon-set.png',
    type: 'file',
    parentId: 'folder-3',
    content: 'binary-image-data-placeholder',
    size: 51200,
    order: 2,
    isPinned: false,
    tags: ['image', 'icons'],
    createdAt: new Date('2024-01-18T11:30:00Z'),
    updatedAt: new Date('2024-01-21T12:00:00Z'),
  },

  // Files in Tests
  {
    id: 'file-20',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Button.test.tsx',
    type: 'file',
    parentId: 'folder-4',
    content: 'import { render } from "@testing-library/react";\nimport { Button } from "../components/Button";\n\ntest("renders button", () => {\n  render(<Button />);\n});',
    size: 1920,
    order: 0,
    isPinned: false,
    tags: ['test', 'component'],
    createdAt: new Date('2024-01-19T13:00:00Z'),
    updatedAt: new Date('2024-01-23T08:45:00Z'),
  },
  {
    id: 'file-21',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'api.test.ts',
    type: 'file',
    parentId: 'folder-4',
    content: 'import { fetchUsers } from "../api/users";\n\ntest("fetches users", async () => {\n  const users = await fetchUsers();\n  expect(users).toBeDefined();\n});',
    size: 2100,
    order: 1,
    isPinned: false,
    tags: ['test', 'api'],
    createdAt: new Date('2024-01-20T09:00:00Z'),
    updatedAt: new Date('2024-01-22T11:00:00Z'),
  },
  {
    id: 'file-22',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'utils.test.ts',
    type: 'file',
    parentId: 'folder-4',
    content: 'import { formatDate } from "../utils/date";\n\ntest("formats date correctly", () => {\n  expect(formatDate(new Date())).toMatch(/\\d{4}-\\d{2}-\\d{2}/);\n});',
    size: 1750,
    order: 2,
    isPinned: false,
    tags: ['test', 'utils'],
    createdAt: new Date('2024-01-20T10:30:00Z'),
    updatedAt: new Date('2024-01-21T14:30:00Z'),
  },

  // Additional root-level files
  {
    id: 'file-23',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'tsconfig.json',
    type: 'file',
    parentId: null,
    content: '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "ESNext"\n  }\n}',
    size: 768,
    order: 7,
    isPinned: false,
    tags: ['config', 'typescript'],
    createdAt: new Date('2024-01-15T09:30:00Z'),
    updatedAt: new Date('2024-01-19T11:00:00Z'),
  },
  {
    id: 'file-24',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'CHANGELOG.md',
    type: 'file',
    parentId: null,
    content: '# Changelog\n\n## v1.0.0\n- Initial release',
    size: 640,
    order: 8,
    isPinned: false,
    tags: ['documentation', 'versioning'],
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-23T13:00:00Z'),
  },
  {
    id: 'file-25',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'LICENSE',
    type: 'file',
    parentId: null,
    content: 'MIT License\n\nCopyright (c) 2024',
    size: 320,
    order: 9,
    isPinned: false,
    tags: ['legal'],
    createdAt: new Date('2024-01-15T09:00:00Z'),
    updatedAt: new Date('2024-01-15T09:00:00Z'),
  },

  // Additional nested folder
  {
    id: 'folder-9',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Hooks',
    type: 'folder',
    parentId: 'folder-2',
    order: 2,
    isPinned: false,
    tags: ['react', 'utilities'],
    createdAt: new Date('2024-01-20T11:00:00Z'),
    updatedAt: new Date('2024-01-23T10:30:00Z'),
  },

  // Files in Components/Hooks
  {
    id: 'file-26',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'useAuth.ts',
    type: 'file',
    parentId: 'folder-9',
    content: 'import { useState } from "react";\n\nexport const useAuth = () => {\n  const [user, setUser] = useState(null);\n  return { user, setUser };\n};',
    size: 1400,
    order: 0,
    isPinned: true,
    tags: ['hook', 'authentication'],
    createdAt: new Date('2024-01-20T12:00:00Z'),
    updatedAt: new Date('2024-01-23T09:15:00Z'),
  },
  {
    id: 'file-27',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'useFetch.ts',
    type: 'file',
    parentId: 'folder-9',
    content: 'import { useState, useEffect } from "react";\n\nexport const useFetch = (url: string) => {\n  const [data, setData] = useState(null);\n  useEffect(() => {\n    fetch(url).then(r => r.json()).then(setData);\n  }, [url]);\n  return data;\n};',
    size: 1850,
    order: 1,
    isPinned: false,
    tags: ['hook', 'data-fetching'],
    createdAt: new Date('2024-01-20T13:00:00Z'),
    updatedAt: new Date('2024-01-22T15:45:00Z'),
  },
  {
    id: 'file-28',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'useLocalStorage.ts',
    type: 'file',
    parentId: 'folder-9',
    content: 'import { useState } from "react";\n\nexport const useLocalStorage = (key: string, initialValue: any) => {\n  const [value, setValue] = useState(() => {\n    return localStorage.getItem(key) || initialValue;\n  });\n  return [value, setValue];\n};',
    size: 2050,
    order: 2,
    isPinned: false,
    tags: ['hook', 'storage'],
    createdAt: new Date('2024-01-21T08:30:00Z'),
    updatedAt: new Date('2024-01-23T11:00:00Z'),
  },

  // Additional nested folder in Assets
  {
    id: 'folder-10',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Icons',
    type: 'folder',
    parentId: 'folder-3',
    order: 3,
    isPinned: false,
    tags: ['svg', 'icons'],
    createdAt: new Date('2024-01-19T14:00:00Z'),
    updatedAt: new Date('2024-01-22T10:00:00Z'),
  },

  // Files in Assets/Icons
  {
    id: 'file-29',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'check.svg',
    type: 'file',
    parentId: 'folder-10',
    content: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M5 13l4 4L19 7" /></svg>',
    size: 384,
    order: 0,
    isPinned: false,
    tags: ['icon', 'svg'],
    createdAt: new Date('2024-01-19T15:00:00Z'),
    updatedAt: new Date('2024-01-19T15:00:00Z'),
  },
  {
    id: 'file-30',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'close.svg',
    type: 'file',
    parentId: 'folder-10',
    content: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M6 6l12 12M18 6L6 18" /></svg>',
    size: 420,
    order: 1,
    isPinned: false,
    tags: ['icon', 'svg'],
    createdAt: new Date('2024-01-19T15:10:00Z'),
    updatedAt: new Date('2024-01-19T15:10:00Z'),
  },
  {
    id: 'file-31',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'menu.svg',
    type: 'file',
    parentId: 'folder-10',
    content: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M3 6h18M3 12h18M3 18h18" /></svg>',
    size: 456,
    order: 2,
    isPinned: false,
    tags: ['icon', 'svg'],
    createdAt: new Date('2024-01-19T15:20:00Z'),
    updatedAt: new Date('2024-01-21T09:30:00Z'),
  },

  // More root files
  {
    id: 'file-32',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'vite.config.ts',
    type: 'file',
    parentId: null,
    content: 'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n});',
    size: 1280,
    order: 10,
    isPinned: false,
    tags: ['config', 'build'],
    createdAt: new Date('2024-01-16T08:00:00Z'),
    updatedAt: new Date('2024-01-20T14:00:00Z'),
  },
  {
    id: 'file-33',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: '.env.example',
    type: 'file',
    parentId: null,
    content: 'API_KEY=your_api_key_here\nDATABASE_URL=your_database_url',
    size: 580,
    order: 11,
    isPinned: false,
    tags: ['config', 'environment'],
    createdAt: new Date('2024-01-16T09:00:00Z'),
    updatedAt: new Date('2024-01-16T09:00:00Z'),
  },

  // Additional files in Documentation
  {
    id: 'file-34',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'architecture.md',
    type: 'file',
    parentId: 'folder-1',
    content: '# Architecture\n\nOverview of the system architecture and design patterns.',
    size: 4500,
    order: 2,
    isPinned: false,
    tags: ['architecture', 'design'],
    createdAt: new Date('2024-01-17T12:00:00Z'),
    updatedAt: new Date('2024-01-22T13:30:00Z'),
  },
  {
    id: 'file-35',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'contributing.md',
    type: 'file',
    parentId: 'folder-1',
    content: '# Contributing Guide\n\nGuidelines for contributing to the project.',
    size: 3300,
    order: 3,
    isPinned: false,
    tags: ['documentation', 'community'],
    createdAt: new Date('2024-01-18T09:00:00Z'),
    updatedAt: new Date('2024-01-21T16:00:00Z'),
  },

  // Files in a deeper nested structure
  {
    id: 'folder-11',
    userId: 'user-123',
    projectId: 'project-alpha',
    name: 'Utils',
    type: 'folder',
    parentId: 'folder-2',
    order: 3,
    isPinned: false,
    tags: ['utilities', 'helpers'],
    createdAt: new Date('2024-01-21T10:00:00Z'),
    updatedAt: new Date('2024-01-23T14:00:00Z'),
  },{
  id: 'file-36',
  userId: 'user-123',
  projectId: 'project-alpha',
  name: 'formatDate.ts',
  type: 'file',
  parentId: 'folder-11',
  content: 'export const formatDate = (date: Date): string => {\n  return date.toISOString().split("T")[0];\n};',
  size: 980,
  order: 0,
  isPinned: false,
  tags: ['utility', 'date'],
  createdAt: new Date('2024-01-21T11:00:00Z'),
  updatedAt: new Date('2024-01-22T12:30:00Z'),
  },
  {
  id: 'file-37',
  userId: 'user-123',
  projectId: 'project-alpha',
  name: 'debounce.ts',
  type: 'file',
  parentId: 'folder-11',
  content: 'export const debounce = (fn: Function, delay: number) => {\n  let timeout: NodeJS.Timeout;\n  return (...args: any[]) => {\n    clearTimeout(timeout);\n    timeout = setTimeout(() => fn(...args), delay);\n  };\n};',
  size: 1250,
  order: 1,
  isPinned: false,
  tags: ['utility', 'performance'],
  createdAt: new Date('2024-01-21T12:00:00Z'),
  updatedAt: new Date('2024-01-23T10:00:00Z'),
  },
  {
  id: 'file-38',
  userId: 'user-123',
  projectId: 'project-alpha',
  name: 'validators.ts',
  type: 'file',
  parentId: 'folder-11',
  content: 'export const isEmail = (email: string): boolean => {\n  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);\n};\n\nexport const isValidUrl = (url: string): boolean => {\n  try {\n    new URL(url);\n    return true;\n  } catch {\n    return false;\n  }\n};',
  size: 1680,
  order: 2,
  isPinned: false,
  tags: ['utility', 'validation'],
  createdAt: new Date('2024-01-22T08:00:00Z'),
  updatedAt: new Date('2024-01-23T12:00:00Z'),
  },
  // Final files
  {
  id: 'file-39',
  userId: 'user-123',
  projectId: 'project-alpha',
  name: 'jest.config.js',
  type: 'file',
  parentId: null,
  content: 'module.exports = {\n  preset: "ts-jest",\n  testEnvironment: "jsdom",\n};',
  size: 890,
  order: 12,
  isPinned: false,
  tags: ['config', 'testing'],
  createdAt: new Date('2024-01-17T13:00:00Z'),
  updatedAt: new Date('2024-01-19T14:30:00Z'),
  },
  {
  id: 'file-40',
  userId: 'user-123',
  projectId: 'project-alpha',
  name: 'tailwind.config.js',
  type: 'file',
  parentId: null,
  content: 'module.exports = {\n  content: ["./src/**/*.{js,jsx,ts,tsx}"],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};',
  size: 1150,
  order: 13,
  isPinned: false,
  tags: ['config', 'styling'],
  createdAt: new Date('2024-01-17T14:00:00Z'),
  updatedAt: new Date('2024-01-21T11:45:00Z'),
  },
  ];
