import { Story } from '../models/story';
import { StoryDetails } from '../models/story-detail';
import { StoryDetailDTO } from './dto/story-detail.dto';
import { StoryGenre } from '../constants';
import { StoryDTO } from './dto/story.dto';
export const mockStories: StoryDetailDTO[] = [
  {
    id: 'story_1',
    series_id: 'series_1',
    user_id: 'user_1',
    title: 'Neon Ashes',
    synopsis:
      'In a cyberpunk city drowning in synthetic rain, a rogue engineer uncovers a conspiracy that blurs the line between human memory and machine control.',
    cover_image: null,
    genre: ['Cyberpunk', 'Thriller'] as StoryGenre[],
    status: 1,
    sync_status: 2,
    created_at: '2026-01-10T10:00:00Z',
    last_updated: '2026-06-20T14:30:00Z',
    deleted_at: null,
    is_archived: true,
    order: 1,
  },
  {
    id: 'story_2',
    series_id: null,
    user_id: 'user_1',
    title: 'The Hollow Crown',
    synopsis:
      'A forgotten heir is forced into a fractured kingdom where magic is dying and political alliances are more dangerous than war.',
    cover_image: null,
    genre: ['Fantasy', 'Mystery'] as StoryGenre[],
    status: 0,
    sync_status: 1,
    created_at: '2026-02-01T12:00:00Z',
    last_updated: '2026-02-10T09:15:00Z',
    deleted_at: null,
    is_archived: false,
    order: 2,
  },
  {
    id: 'story_3',
    series_id: 'series_2',
    user_id: 'user_2',
    title: 'Black Salt Protocol',
    synopsis:
      'A deep-sea research station goes silent after discovering an unknown biological signal beneath the ocean floor.',
    cover_image: null,
    genre: ['Horror', 'Sci-Fi'] as StoryGenre[],
    status: 1,
    sync_status: 2,
    created_at: '2025-11-05T08:00:00Z',
    last_updated: '2026-05-12T18:45:00Z',
    deleted_at: null,
    is_archived: false,
    order: 6,
  },
  {
    id: 'story_4',
    series_id: null,
    user_id: 'user_3',
    title: 'Glass Orbit',
    synopsis:
      'On a failing space habitat, a maintenance worker discovers the station is quietly rewriting its own systems—and possibly its inhabitants.',
    cover_image: null,
    genre: ['Sci-Fi', 'Thriller'] as StoryGenre[],
    status: 0,
    sync_status: 0,
    created_at: '2026-03-22T16:20:00Z',
    last_updated: '2026-03-22T16:20:00Z',
    deleted_at: null,
    is_archived: false,
    order: 3,
  },
  {
    id: 'story_5',
    series_id: 'series_3',

    user_id: 'user_1',
    title: 'Echoes of Emberlight',
    synopsis:
      'Two rival factions in a dying world must reluctantly cooperate when an ancient force begins consuming reality itself.',
    cover_image: null,
    genre: ['Fantasy', 'Biopunk'] as StoryGenre[],
    status: 3,
    sync_status: 3,
    created_at: '2025-06-14T11:00:00Z',
    last_updated: '2025-12-01T09:00:00Z',
    deleted_at: null,
    is_archived: false,
    order: 4,
  },
  {
    id: 'story_6',
    series_id: null,
    user_id: 'user_2',
    title: 'Static Hearts',
    synopsis:
      'A romance between two people who only ever meet through fragmented digital messages in a collapsing communication network.',
    cover_image: null,
    genre: ['Romance', 'Sci-Fi'] as StoryGenre[],
    status: 2,
    sync_status: 2,
    created_at: '2025-08-30T13:45:00Z',
    last_updated: '2026-01-15T20:10:00Z',
    deleted_at: null,
    is_archived: false,
    order: 5,
  },
];
