export { mockSeries } from "./mockdata"
export type { Series } from "./model/series"
export { useCreateSeriesMutation } from "./api/mutations/useCreateSeriesMutation"
export { useDeleteSeriesMutation } from "./api/mutations/useDeleteSeriesMutation"
export { useReorderStoriesMutation } from "./api/mutations/useReorderStoriesMutation"
export {useUpdateSeriesMutation} from "./api/mutations/useUpdateSeriesMutation"
export { useSeriesDetailQuery } from "./api/queries/useSeriesDetailQuery"
export {useSeriesQuery} from "./api/queries/useSeriesQuery"